version: 2.1

orbs:
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@3.1.1

defaults: &defaults
  docker: # executor type
    - image: cimg/node:13.8.0

jobs:
  myJob1:
    <<: *defaults
    steps:
      - checkout
      - run: echo "hello world"

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5} \
              --region us-east-1

workflows:
  myWorkflow:
    jobs:
      - myJob1
      # - create_infrastructure
