version: 2.1

orbs:
  # welcome: circleci/welcome-orb@0.4.1
  aws-cli: circleci/aws-cli@3.1.1

defaults: &defaults
  docker: # executor type
    - image: cimg/node:13.8.0

commands:
  # Exercise - Rollback
  destroy_environment:
    steps:
      - run:
          name: Destroy environment
          # ${CIRCLE_WORKFLOW_ID} is a Built-in environment variable
          # ${CIRCLE_WORKFLOW_ID:0:5} takes the first 5 chars of the variable CIRCLE_CI_WORKFLOW_ID
          when: on_fail
          command: |
            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:5}

jobs:
  myJob1:
    <<: *defaults
    steps:
      - checkout
      - run: echo "hello world"

  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create Cloudformation Stack
          command: |
            aws cloudformation deploy \
              --template-file template.yml \
              --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7} \
              --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11 # for ansible
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ['fc:04:92:9d:f8:09:bf:5e:00:fd:1a:6f:30:42:5e:8e']
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
          name: smoke test
          # command: |
          #   URL="https://blog.udacity.com/" #env variable
          #   # Test if website exists
          #   if curl -s --head ${URL}
          #   then
          #     return 0
          #   else
          #     return 1
          #   fi
          command: return 1 # to fail the test intentionally
      - destroy_environment

workflows:
  myWorkflow:
    jobs:
      # - myJob1
      - create_infrastructure
      # - configure_infrastructure
      - smoke_test:
          requires:
            - 'create_infrastructure'
