version: 2.1

jobs:
  save_hello_world_output:
    docker: # executor type
      - image: cimg/node:13.8.0
    steps:
      - run:
          name: 'Save hello world output'
          command: echo "text to output here" > output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker: # executor type
      - image: cimg/node:13.8.0
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: 'Print hello world output'
          command: cat output.txt

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  save_and_print_workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
